name: Testing multi-folder project

on:
  push:
    branches:
      - testing

jobs:
  run-jest-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: cd server && npm ci
      - run: npm test
